# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample
  flutter_application_path = '../my_sample_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

 
  install_all_flutter_pods(flutter_application_path)
  

  target 'sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
